### ISSUE TITLE
is this already useable as zarr backend?

### ISSUE THREAD

**Issue by vincentschut** [martindurant/gcsfs#1]
more a question than an issue: I found this while looking for a s3fs (dask/s3fs) alternative to be used as zarr backend. We are looking to make our processing less dependend on AWS. Would you say gcsfs is already useable as a s3fs replacement for zarr?

(edit: sorry for the confusion, I typed 's3ql' instead of 's3fs' the first time. Corrected now.)

**Comment by martindurant** [comment]
This project is obviously very much alpha - there has not been any one to experiment with it except for myself, and there is no documentation yet except for docstrings.

However, the intent is to have gcsfs become as stable as s3fs and hdfs3, it is only a matter of time. 
The GCSMapper class I believe does function as advertised, so zarr should work with it fine. In fact, I have a small side-project to save Xarrays (netCDF-like) into zarrs, and I just tested it by round-tripping real data.

If I can help accelerate your work with zarr and gcsfs, don't hesitate to raise issues as they arise.

**Comment by martindurant** [comment]
Note that listing a bucket only promises eventual consistency in GCS, if the bucket is set as multi-region. This is a problem for writing and immediately re-reading from a GCSMapping, so you might want to ensure you are using single-region in this case.

**Comment by vincentschut** [comment]
Thanks for the info. I'll soon start some experiments, I'll let you know in case of issues. And i'll make sure we work on a single-region bucket, just to be sure. No real need for multi-region anyway in this context.
